export type Country = {
	code: string;
	name: string;
};

export const COUNTRIES: Country[] = [
	{ code: "NO", name: "Norway" },
	{ code: "SE", name: "Sweden" },
	{ code: "DK", name: "Denmark" },
	{ code: "FI", name: "Finland" },
	{ code: "IS", name: "Iceland" },
	{ code: "DE", name: "Germany" },
	{ code: "NL", name: "Netherlands" },
	{ code: "BE", name: "Belgium" },
	{ code: "FR", name: "France" },
	{ code: "ES", name: "Spain" },
	{ code: "IT", name: "Italy" },
	{ code: "GB", name: "United Kingdom" },
	{ code: "IE", name: "Ireland" },
	{ code: "PT", name: "Portugal" },
	{ code: "CH", name: "Switzerland" },
	{ code: "AT", name: "Austria" },
	{ code: "CZ", name: "Czech Republic" },
	{ code: "SK", name: "Slovakia" },
	{ code: "HU", name: "Hungary" },
	{ code: "SI", name: "Slovenia" },
	{ code: "HR", name: "Croatia" },
	{ code: "BA", name: "Bosnia and Herzegovina" },
	{ code: "RS", name: "Serbia" },
	{ code: "ME", name: "Montenegro" },
	{ code: "MK", name: "North Macedonia" },
	{ code: "BG", name: "Bulgaria" },
	{ code: "RO", name: "Romania" },
	{ code: "GR", name: "Greece" },
	{ code: "TR", name: "Turkey" },
	{ code: "PL", name: "Poland" },
	{ code: "EE", name: "Estonia" },
	{ code: "LV", name: "Latvia" },
	{ code: "LT", name: "Lithuania" },
	{ code: "XK", name: "Kosovo" },
	{ code: "US", name: "United States" },
	{ code: "CA", name: "Canada" },
	{ code: "BR", name: "Brazil" },
	{ code: "AR", name: "Argentina" },
	{ code: "CL", name: "Chile" },
	{ code: "MX", name: "Mexico" },
	{ code: "AU", name: "Australia" },
	{ code: "NZ", name: "New Zealand" },
	{ code: "CN", name: "China" },
	{ code: "JP", name: "Japan" },
	{ code: "KR", name: "South Korea" },
	{ code: "IN", name: "India" },
	{ code: "SG", name: "Singapore" },
	{ code: "HK", name: "Hong Kong" },
	{ code: "ZA", name: "South Africa" },
];
